image: node:10.15

stages:
  - test
  - build
  - deploy
  
lint:
  stage: test
  script:
  - npm install
  - npm run lint

unit-testing:
  stage: test
  script:
  - npm install
  - npm test

build-test:
  stage: test
  script:
  - npm install
  - npm run build
